package drools.presentation.rules

import drools.presentation.models.User;

rule "Hello To User 1"
	agenda-group "agenda 1"
	ruleflow-group "group 1"
	auto-focus true
when
    $user : User()
then
    System.out.println("Executed: "+ drools.getRule().getName());  
end

rule "Print message for unauthorized users"
	agenda-group "agenda 2"
	ruleflow-group "group 1"
when
    $p : User()
then
    System.out.println("Executed: "+ drools.getRule().getName()); 
end